version: '3.8'
volumes:
  data:
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: arci
      MYSQL_USER: arci
      MYSQL_PASSWORD: Arci2023
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3308:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    
    restart: always
    volumes:
      - .:/app/
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  ngrok:
    image: wernight/ngrok
    volumes:
      - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    ports:
      - "4040:4040"
    restart: always
    command: ["ngrok", "http", "backend:8000"]


